import "@picocss/pico";
import "./style.css"
import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";

const fontFamily = Comfortaa({subsets: ['latin']})

export const metadata: Metadata = {
  title: "Etiquetas",
  description: "Generated by create next app",
};

export default function FormLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={fontFamily.className}>{children}</body>
    </html>
  );
}
